app/boot.ts, app/components/app.ts, app/components/home.ts, app/styles/index.scss, app/styles/index.ts, app/styles/mixins.scss, app/styles/style.scss, app/styles/variables.scss, app/views/home.html, public/index.html
Lay down the initial base for the home page so that at least something is runnable.
=> feat(home): lay base for the home page

npm-shrinkwrap.json
Add a shrinkwrap so unwanted updates don't occur.
=> chore(npm): add shrinkwrap file

app/boot.ts, app/styles/main.scss, app/styles/mixins.scss, app/styles/tracker.scss, app/styles/variables.scss, app/views/info.html
=> feat(info): base for info panel

app/components/box.ts, app/components/dex.ts, app/components/header.ts, app/styles/main.scss, app/styles/tracker.scss, app/styles/variables.scss, app/views/box.html, app/views/dex.html, app/views/header.html
=> feat(dex): dex header

app/components/box.ts, app/components/pokemon.ts, app/styles/tracker.scss, app/styles/variables.scss, app/views/box.html, app/views/pokemon.html
=> feat(dex): boxes base!!!

app/styles/tracker.scss, app/styles/variables.scss, app/views/header.html, app/views/info.html, app/views/pokemon.html, package.json
=> feat(tracker): responsiveness!

app/styles/mixins.scss, app/styles/tracker.scss
=> fix(tracker): fix scrolling for mobile

app/boot.ts, app/classes/pokemon.ts, app/components/box.ts, app/components/dex.ts, app/components/pokemon.ts, app/components/tracker.ts, app/pipes/group.ts, app/pipes/number.ts, app/services/pokemon.ts, app/views/box.html, app/views/dex.html, app/views/pokemon.html, app/views/tracker.html
=> feat(pokemon): fetch pokemon from the API

app/components/box.ts, app/components/dex.ts, app/components/info.ts, app/components/pokemon.ts, app/components/tracker.ts, app/views/box.html, app/views/dex.html, app/views/info.html, app/views/pokemon.html, app/views/tracker.html
〜(￣▽￣〜)
(〜￣▽￣)〜
~(‾⌣‾~)
(~‾⌣‾)~
=> Change info

app/components/app.ts, app/components/login.ts, app/components/register.ts, app/styles/main.scss, app/styles/tracker.scss, app/styles/variables.scss, app/views/login.html, app/views/register.html
=> feat(register): base for register

app/components/login.ts, app/components/register.ts, app/styles/main.scss, app/views/login.html, app/views/register.html
（*’∀’人）♥
fixes https://github.com/robinjoseph08/pokedextracker.com/issues/14
=> feat(login): login base

app/components/login.ts, app/services/pokemon.ts, app/services/session.ts, app/views/login.html
♪(((#^-^)八(^_^*)))♪
easy peasy lemon squeezy
fixes #27
=> feat(login): hook up login

npm-shrinkwrap.json, package.json, public/index.html
ϞϞ(๑⚈ ․̫ ⚈๑)∩
this also happens to fix the firefox issue :+1: 
fixes #42
=> chore(angular2): update from beta.9 -> beta.12

app/components/box.ts, app/components/dex.ts, app/components/info.ts, app/components/pokemon.ts, app/styles/tracker.scss, app/views/box.html, app/views/dex.html, app/views/info.html, app/views/login.html, app/views/pokemon.html, app/views/register.html, app/views/tracker.html
(:ᘌꇤ⁐ꃳ 三
fixes https://github.com/robinjoseph08/pokedextracker.com/issues/20
=> fix(dex): replace hover ux with clicks

app/classes/pokemon.ts, app/components/box.ts, app/components/dex.ts, app/components/header.ts, app/components/pokemon.ts, app/styles/tracker.scss, app/views/box.html, app/views/dex.html, app/views/header.html
=> feat(dex): add region toggling capabilities

app/classes/pokemon.ts, app/styles/tracker.scss, app/views/info.html, app/views/pokemon.html
ʕ ⊃･ ◡ ･ ʔ⊃
this still needs your styles cause right now, they're pretty darn huge
fixes #12
=> fix(font): use font awesome male and female signs

public/index.html
=> feat(analytics): add google analytics

app/styles/main.scss, app/views/header.html, app/views/login.html, app/views/register.html
˛˛ƪ(⌾⃝ ౪ ⌾⃝ ๑)و ̉ ̉
for our USERS
=> feat(dex): show alpha warning

public/index.html
(๑•̌.•̑๑)ˀ̣ˀ̣
- i know this isn't super important right now, but i cant stop thinking about it so ima do it anyway
- gots some infos from [here](https://support.google.com/gsa/answer/6329200#2ca1bec8-9cb6-4e70-a959-8993bc3d4a61)
- if you think any copy should change, lmk
=> chore(description): update the description meta tag

app/components/box.ts, app/components/header.ts, app/components/nav.ts, app/components/pokemon.ts, app/styles/main.scss, app/styles/tracker.scss, app/views/box.html, app/views/dex.html, app/views/header.html, app/views/nav.html, app/views/tracker.html
(っ- ‸ – ς)
^ sad because angular 2 is confuzzling
fixes https://github.com/robinjoseph08/pokedextracker.com/issues/50
i need a `viewing` class on `<pokemon>` if someone is viewing in order to disable the hover effects. but i couldn't get the angular part to work lolol. can you help me add that? the css is already set up with the class `viewing`.
=> feat(tracker): design view only mode

app/views/nav.html
ヽ｀、、ヽ｀ヽ｀、ヽ｀、ヽ｀｀｀、ヽ｀｀、ヽ｀、ヽ｀ヽ｀、、ヽ｀ヽ｀、ヽ｀、ヽ｀｀、ヽ｀、ヽ｀ヽ｀、、ヽ｀ヽ｀、ヽ｀、ヽ｀｀、ヽ｀、ヽ｀ヽ｀、、ヽ｀ヽ｀、ヽ(ノ；Д；)ノ ｀、、:umbrella: ヽ｀ヽ｀、ヽ｀｀、ヽ｀、ヽ｀ヽ｀、｀、ヽ｀｀、ヽ｀、ヽ｀ヽ｀、、ヽ｀ヽ｀、ヽ｀、ヽ｀｀、ヽ｀、ヽ｀ヽ｀、、ヽ｀ヽヽ｀、ヽ｀｀、ヽ｀、ヽ｀ヽ｀、、ヽ｀ヽ｀｀、ヽ｀、ヽ｀ヽ｀、、ヽ｀ヽ｀｀、ヽ｀｀、
^ to commemorate the rainy weekend
fixes #75
=> fix(nav): link to your tracker if logged in

app/classes/capture.ts, app/components/info.ts, app/components/tracker.ts, app/services/capture.ts, app/services/pokemon.ts
=> fix(info): load pokemon info if it hasn't been loaded already

public/index.html
=> fix(number): polyfill intl because of browser compat

app/classes/evolution-family.ts, app/classes/evolution.ts, app/classes/pokemon.ts, app/components/evolution-family.ts, app/components/evolutions.ts, app/components/info.ts, app/pipes/capitalize.ts, app/styles/main.scss, app/styles/mixins.scss, app/styles/tracker.scss, app/styles/variables.scss, app/views/evolution-family.html, app/views/evolutions.html, app/views/info.html
“:♡.•♬✧⁽⁽ଘ( ˊᵕˋ )ଓ⁾⁾*+:•*∴
fixes #69 
fixes #71
=> feat(evolutions): hook up evolutions

public/sitemap.xml
=> feat(sitemap): add sitemap

app/styles/main.scss, app/styles/tracker.scss, app/views/header.html
(((＼（＠v＠）／)))
fixes https://github.com/robinjoseph08/pokedextracker.com/issues/93
can you add the auto select input on click?
=> feat(header): add share link

app/classes/capture.ts, app/components/info.ts, app/styles/main.scss, app/styles/tracker.scss, app/views/info.html, app/views/tracker.html, public/index.html
¯\_༼ ಥ ‿ ಥ ༽_/¯
fixes https://github.com/robinjoseph08/pokedextracker.com/issues/22
i can't get the loading part in `info.ts` to work lol. fix itttt
=> fix(tracker): loading text

app/components/box.ts, app/services/capture.ts, app/styles/tracker.scss, app/views/box.html
fixes https://github.com/robinjoseph08/pokedextracker.com/issues/16
needs to be connected to the back-end. i'm thinking that it will change from "mark all" to "unmark all" if you have the whole box already. also, while the request is happening, it'd be cool to disable the button and replace the content with a spinner of some sort?
=> feat(box): mark/unmark entire box

app/components/home.ts, app/components/tracker.ts
゜｡ᕕ( ≧ ω ≦)／゜｡
^ I MADE DIS: http://japaneseemoticons.me/kamoji/
=> fix(title): clean up titles

app/styles/home.scss, app/styles/main.scss, app/styles/tracker.scss, app/views/login.html, app/views/register.html
:: (•ᴥ• )́`́’́`́’⻍
^ porcupine
fixes https://github.com/robinjoseph08/pokedextracker.com/issues/87
=> fix(responsiveness): iphone 5 width

app/styles/main.scss, app/styles/tracker.scss, app/views/info.html, public/index.html
（：。）ミ
^ i shall call him squishy and he shall be mine and he shall be my squishy
fixes #55
=> feat(no-touch): add no-touch class if not on mobile

app/styles/main.scss, app/styles/tracker.scss, public/index.html
=> fix(tracker): fix sizing

public/index.html
=> feat(seo): add site name

app/views/register.html
=> fix(register): fix friend_code

app/classes/user.ts, app/components/register.ts
┻┳|･ω･)ﾉ
adds saving the referrer on signup. here's a redirect link to [localhost:8080](http://goo.gl/fT3cc4) so that it sets the value of `document.referrer` when youre running locally (you should open console and type `document.referrer` to make sure it's set). then register. then i can either give you staging db access or i can verify it worked for you.
=> feat(register): send referrer

app/classes/evolution-family.ts, app/components/evolution-family.ts, app/components/info.ts, app/components/tracker.ts, app/services/pokemon.ts, app/styles/tracker.scss, app/views/evolution-family.html, app/views/info.html, app/views/pokemon.html
(੭ु˙꒳​˙)੭ु⁾⁾
fixes #95 
idk if i was supposed to add the `cursor: pointer` or just add an empty `href` ¯\\\_(ツ)_/¯ if the `href` is preferred, i can change it.
also, idk if we want an active state or something. 
another thing to note is the fact that i can still click on a selected pokemon and it will "reload". should we disable that or is it not a big deal? i dont really see any harm in it. what do you think?
=> feat(evolutions): add links to the pokemon

.travis.yml, README.md, app/components/home.ts, app/components/info.ts, npm-shrinkwrap.json, package.json, tslint.json
⁽(◍˃̵͈̑ᴗ˂̵͈̑)⁽
just updated tslint and added a few more rules! i also wanted to enable travis at least for linting. just for funsies!
=> chore(lint): update tslint from 3.6.0 to 3.13.0

app/classes/pokemon.ts
Hi there. Love the project. Just wanted to add a suggestion.
I seriously love checking for info at serebii over bulbapedia. I use it often to find information on breeding, catching, held item and more.
This is an ugly PR but it's here just to make it work. Let me know if what you think. I'm fine if it's declined. Even better if you could point me in the right direction to make this happen.
I assume a PR is better than creating an issue to suggest a feature. 😄
=> feat(dex): added serebii link

app/styles/tracker.scss, app/views/info.html
=> feat(info): add btn to serebii

npm-shrinkwrap.json
=> fix(shrinkwrap): remove references to nodejitsu

app/styles/home.scss, app/views/home.html
=> feat(twitter): add twitter link

CONTRIBUTING.md
=> docs(contributing): add CONTRIBUTING.md

app/classes/user.ts, app/components/account.ts, app/components/app.ts, app/components/header.ts, app/components/nav.ts, app/components/register.ts, app/services/user.ts, app/styles/main.scss, app/styles/tracker.scss, app/styles/variables.scss, app/views/account.html, app/views/header.html, app/views/login.html, app/views/nav.html, app/views/register.html
=> feat(account): add functionality to the account page

app/styles/tracker.scss, app/views/header.html
=> feat(share): link to tweet

app/styles/home.scss, app/styles/pokesprite.scss, app/views/home.html
♡〜٩(^▿^)۶〜♡
fixes https://github.com/robinjoseph08/pokedextracker.com/issues/159
added some manual styles since this is the only one of the "non-pokemon" sprites we're using
=> fix(home): replace loveball w pokesprite

app/classes/pokemon.ts
٩(˃̶͈̀௰˂̶͈́)و
FIXES #166 
shouldve done it this way to begin with, but this should fix it! you should test it fully across browsers though to make sure
=> fix(pkicon): better class property

app/styles/home.scss, app/styles/main.scss, app/styles/tracker.scss, app/views/account.html, app/views/box.html, app/views/home.html, app/views/login.html, app/views/register.html
(๑•̌.•̑๑)ˀ̣ˀ̣
^ me confused by the css
i attempted to make the more generic `btn` class! arent ya proud? ^_^
that said, i literally have no idea why i had to add that `padding-top: 14px;`. i looked through all of the computed styles of the button on prod and couldnt figure out what styles were missing that made it look like this:
all i know is that `padding-top: 14px;` fixeded it. so if there's a better way, just lmk and ill do that lol. but everything else looks good though!
=> refactor(buttons): add .btn styles

app/styles/home.scss, app/styles/main.scss, app/views/account.html, app/views/box.html, app/views/home.html, app/views/login.html, app/views/register.html
(((＼（＠v＠）／)))
- now that we have 3 different colors of btns, create better, reusable classes for them.
- also fixes a bug in prod where the `focus` state of the white button was blue (right click on the "Register" button on the home page)
fixes https://github.com/robinjoseph08/pokedextracker.com/issues/175
=> refactor(buttons): better btn styles

.gitignore, app/boot.ts, app/components/account.ts, app/components/login.ts, app/components/register.ts, app/components/reload.ts, app/components/tracker.ts, app/services/api.ts, app/services/version.ts, app/styles/main.scss, app/views/account.html, app/views/login.html, app/views/register.html, app/views/reload.html, app/views/tracker.html, package.json, tslint.json
⌒°(ᴖ◡ᴖ)°⌒
fixes https://github.com/robinjoseph08/pokedextracker.com/issues/158
=> feat(reload): add reload component and styles

app/styles/tracker.scss
☆~~ヾ(>▽<)ﾉ｡･☆
fixes https://github.com/robinjoseph08/pokedextracker.com/issues/180
=> fix(info): remove no-touch styles for info btn

.gitignore, app/actions/capture.js, app/actions/pokemon.js, app/actions/session.js, app/actions/user.js, app/actions/utils.js, app/components/login.jsx, app/components/register.jsx, app/components/reload.jsx, app/components/tracker.jsx, app/reducers/index.js, app/reducers/reload.js, app/styles/main.scss, package.json
=> refactor(react): move over reload styles

app/components/account.jsx, app/components/app.jsx, app/components/header.jsx, app/components/info.jsx, app/components/login.jsx, app/components/mark-all-button.jsx, app/components/nav.jsx, app/components/pokemon.jsx, app/components/region.jsx, app/components/register.jsx, app/components/share.jsx, app/utils/analytics.js, config/development.js, config/production.js, config/staging.js, npm-shrinkwrap.json, package.json, public/index.html
(ತ◞౪◟ತ‵)
fixes #186 
checked each event and saw that it registered each one:
the list of all events that should be registered is in the issue, but i think i got everything!
=> refactor(react): add analytics

.gitignore, app/stores/index.js, app/utils/analytics.js, app/utils/local-storage.js, config/development.js, config/production.js, config/staging.js, npm-shrinkwrap.json, package.json, webpack.config.js
“:♡.•♬✧⁽⁽ଘ( ˊᵕˋ )ଓ⁾⁾*+:•*∴
fixes #120 
adds sentry! it's pretty nifty, ill show it to you next time! it'll track username, ip, stack trace, which version of the code they were using, browser/os, and actions leading up to the error.
=> feat(errors): add sentry for error logging

CHANGELOG.md, LICENSE.txt
₍₍ (ง ˙ω˙)ว ⁾⁾
fixing the changelog issue donald mentioned and adding a license since every repo needs a license!
just gonna merge since these are just docs changes lol
=> Docs fixes

app/components/progress.jsx
=> fix(progress): add percentage

app/actions/capture.js, app/actions/dex.js, app/actions/user.js, app/components/dex.jsx, app/components/mark-all-button.jsx, app/components/pokemon.jsx, app/components/progress.jsx, app/components/tracker.jsx, app/reducers/captures.js, app/reducers/current-dex.js, app/reducers/current-user.js, app/reducers/dexes.js, app/reducers/index.js, app/reducers/users.js
=> refactor(dexes): use the dexes API for the tracker page

app/components/app.jsx, app/components/dex-preview.jsx, app/components/dex.jsx, app/components/friend-code.jsx, app/components/header.jsx, app/components/profile.jsx, app/components/progress.jsx, app/components/share.jsx, app/components/tracker.jsx, app/styles/main.scss, app/styles/profile.scss, app/styles/tracker.scss
=> feat(profile): connect profile page

app/actions/dex.js, app/components/account.jsx, app/components/create-dex.jsx, app/components/dex-create.jsx, app/components/login.jsx, app/components/profile.jsx, app/components/register.jsx, app/styles/main.scss, app/styles/variables.scss, npm-shrinkwrap.json, package.json
♫ꉂ (๑¯ਊ¯)σ
- need you do work your stylez magic on this bad boy. the two main class you need to work with are `.modal` and `.modal-overlay`.
- we should probs pull out this form since we use it here and register... oh well.
- i didnt add a loading var to this component since i was going off login/register which dont also, but we can add one if you think we should. i kinda think we should add them to login/register too
=> feat(dex): add create dex modal

app/actions/session.js, app/actions/user.js, app/components/home.jsx, app/components/nav.jsx, app/components/profile.jsx, app/components/tracker.jsx, app/reducers/index.js, app/reducers/session-user.js, app/styles/main.scss
(灬㋭ ਊ ㋲灬)
updates nav and home links for multiple dexes! i THINK it mostly works but there may be random edge cases i'm not sure about ;____;
=> feat(nav): update nav for multiple dexes

app/components/dex-indicator.jsx, app/components/dex-preview.jsx, app/components/header.jsx, app/styles/profile.scss, app/styles/tracker.scss
ヾ(０∀０*★)ﾟ*･.｡
- adds a shiny indicator for shiny dexes! inspired by pokemon's [own way of indicating shiny pokemon](http://i.imgur.com/ndMSJ3e.jpg)
=> feat(dexes): add shiny dex indicator

app/components/share.jsx, app/styles/tracker.scss
=> fix(share): fix share styles

app/actions/dex.js, app/components/alert.jsx, app/components/dex-edit.jsx, app/components/dex-preview.jsx, app/components/form-warning.jsx, app/components/profile.jsx, app/styles/main.scss, app/styles/profile.scss
୧☉□☉୨ THE END IS NEAR
to-do for you to add:
=> feat(dexes): add edit dex modal

app/actions/utils.js, app/components/notification.jsx, app/components/profile.jsx, app/components/register.jsx, app/components/reload.jsx, app/reducers/index.js, app/reducers/notification.js, app/styles/main.scss, app/utils/local-storage.js
୧( ⁼̴̶̤̀ω⁼̴̶̤́ )૭
the functionality has been added, so now it just needs to look pwetty :3
=> feat(notification): add base of notification

app/components/home.jsx, app/styles/home.scss
=> feat(home): update home content

app/reducers/captures.js
=> fix(mark-all): fix mark all button for partially marked box

app/components/profile.jsx
(ง ◕ั⌑◕ั)ว ⁾
hide the notification while leaving the code for future ones!
=> feat(notif): remove 2016-12-10 notif

app/components/dex-create.jsx, app/styles/main.scss
=> feat(create): add region to create dex

app/components/register.jsx
ᕕ〳 ் (oo) ் 〵╯
eventually this stuff should probably become it's own component... but... yea.
=> feat(register): add region to registration

app/components/box.jsx, app/components/dex.jsx, app/styles/tracker.scss, app/utils/pokemon.js
⤴︎ ε=ε=(ง ˃̶͈̀ᗨ˂̶͈́)۶ ⤴︎
- group the boxes according to `pokemon.box`
- use the correct title for the box
- use `pokemon.form` for the sprite
this should be the last pr i think! just gotta make it look pertty
=> feat(boxes): take pokemon.box into account when grouping

app/stores/index.js
This allows you to have all the benefits of redux dev tools, without having to hook middlewares up in your app.
https://github.com/zalmoxisus/redux-devtools-extension
=> Add hook for redux devtools

app/components/evolution-family.jsx
=> Add name of pokemon on hover in evolution chain

package.json
And move babel-core dep into devDeps
Love the switch to yarn! 😄
=> chore(deps): Removed unused direct dependency on json-loader

app/styles/profile.scss, public/index.html
♪(*￣(ｴ)￣)o/￣￣￣￣￣￣~ >ﾟ )))>彡
fixes https://github.com/pokedextracker/pokedextracker.com/issues/254
=> fix(fonts): add semibold montserrat

app/components/dex.jsx, app/components/profile.jsx
¯\\\_༼ ಥ ‿ ಥ ༽_/¯
fixes https://github.com/pokedextracker/pokedextracker.com/issues/265
=> feat(notif): remove alola support notification

app/components/info-locations.jsx, app/components/info.jsx, app/styles/tracker.scss
=> feat(info): show gen 6 for gen 7 national

app/components/dex-edit.jsx
=> fix(edit-dex): only show generation warning when there's loss of info

app/styles/main.scss, app/styles/tracker.scss
₊\*ˈ˚·(๑˃̶̡̢̥ ॣಐ ॣ˂̶̡̢̥๑)·˚ˈ*₊
fixes #100 
fixes #213
=> fix(styles): various style fixes

app/reducers/session.js, app/stores/index.js, app/utils/local-storage.js, app/utils/state.js
⌒⌒　　　⌒ “⊂(　っ☉ω☉)っ
fixes #90 
adds a basic local storage polyfill if local storage isnt available. its not the most complete polyfill, but it suffices for our needs and makes the site at least usable
=> fix(local-storage): make site usable without local storage

app/components/account.jsx, app/components/footer.jsx, app/components/login.jsx, app/components/profile.jsx, app/components/register.jsx, app/components/tracker.jsx, app/styles/main.scss, app/styles/profile.scss, app/styles/tracker.scss
=> feat(footer): add footer

app/styles/main.scss
=> fix(footer): add mobile styles

app/styles/main.scss
┬┴┬┴┤( ͡° ͜ʖ├┬┴┬┴
fixes https://github.com/pokedextracker/pokedextracker.com/issues/285
=> chore(styles): remove border radius from buttons

app/components/info-locations.jsx
٩(•̤̀ᵕ•̤́๑)ᵒᵏᵎᵎᵎᵎ
fixes https://github.com/pokedextracker/pokedextracker.com/issues/284
=> fix(locations): add empty state to locations

SUPPORTERS.md
°₊·ˈ∗♡( ˃̶᷇ ‧̫ ˂̶᷆ )♡∗ˈ‧₊°
add donators to `SUPPORTERS.md`!! i didnt know if i should wrap the usernames in backticks, but i kinda dont think so
=> feat(supporters): add supporters!!

app/components/dex.jsx, app/components/profile.jsx
┌[ ʘ̆ ۝ ʘ̆ ]┐
commented instead of removing so we can easily turn on again in the future
=> chore(notif): remove ultra sun / moon notif

app/components/dex.jsx, app/components/tracker.jsx
=> fix(scroll): fix scroll button

app/actions/search.js, app/components/box.jsx, app/components/dex.jsx, app/components/pokemon.jsx, app/components/search-bar.jsx, app/components/search-results.jsx, app/components/tracker.jsx, app/reducers/index.js, app/reducers/query.js, app/styles/main.scss, app/styles/tracker.scss, app/utils/defer-component-render.jsx, package.json, yarn.lock
(╭☞´ิ∀´ิ)╭☞
fixes https://github.com/pokedextracker/pokedextracker.com/issues/18
@robinjoseph08 added style and component bases, functionality ready to be added! 🎉
=> feat(search): add search element

app/styles/tracker.scss
ฅ(*°ω°*ฅ)
i thought the evolution part was fine so left it!
=> fix(info): fix sprites in info panel

app/styles/home.scss
=> fix(sprites): fix loveball styling

app/components/home.jsx, app/components/notification.jsx, app/utils/state.js
=> feat(swsh): national dex support

app/components/dex-edit.jsx, app/styles/profile.scss
ヾ(´･ ･｀｡)ノ”
dunno why but it works!
fixes #353
=> fix(mobile): make delete dex work

.kube/production.yaml, .kube/staging.yaml, Dockerfile, config/development.js, config/production.js, config/staging.js, hooks/build, hooks/post_push, package.json, scripts/deploy.sh
( ƅ°ਉ°)ƅ
- update kube yaml for the new app helm chart
- be more specific able files copied into the docker context to make a smaller image
- change `api.` domains with `/api` paths
- remove `hooks` directory since we're not gonna be building automatically anymore
- have 1 deploy script for both staging and production
=> feat(deploy): update for new cluster

app/styles/main.scss
got blinded by this one today 😛
=> fix(night-mode): fix reload background in night mode

app/components/box.jsx, app/components/dex-edit.jsx, app/components/home.jsx, app/components/info.jsx, app/components/notification.jsx, app/utils/pokemon.jsx, app/utils/state.js
ミ(・・)ミ
fixes https://github.com/pokedextracker/pokedextracker.com/issues/355 https://github.com/pokedextracker/pokedextracker.com/issues/357 https://github.com/pokedextracker/pokedextracker.com/issues/350
=> feat(boxes): handle sword/shield expansion pass

app/actions/capture.js, app/actions/dex-type.js, app/components/box.jsx, app/components/dex-create.jsx, app/components/dex-edit.jsx, app/components/dex-indicator.jsx, app/components/info.jsx, app/components/profile.jsx, app/components/register.jsx, app/reducers/dex-types-by-game-family-id.js, app/reducers/dex-types-by-id.js, app/reducers/games-by-id.js, app/reducers/index.js, package.json
- change the default port to 9898 for less conflicts
- stop using and passing around `dex.regional`
=> feat(dex-type): add the concept of dex type to replace explicit regionality

app/components/info.jsx
add an entry for bdsp serebii links
=> fix(bdsp): add serebii link for BDSP

app/components/home.jsx, app/components/notification.jsx, app/utils/state.js
=> feat(bdsp): launch

app/actions/capture.js, app/components/pokemon.jsx, app/reducers/captures.js, app/reducers/dexes.js, app/reducers/users.js, app/styles/main.scss, app/styles/tracker.scss
While an API call is in-progress, add a 'pending' class which is a gradient between two colors.
This provides the user with an acknowledgement of the action while API calls may be pending.
Fixes #433
An example of how this looks is the Pachirisu shown in the screenshot below.
=> feat(box): add intemediate state for each Pokemon cell

app/components/home.jsx, app/components/notification.jsx, app/utils/state.js
=> feat(arceus): launch

app/components/info.jsx
add slug for legends arceus since that was missed
fixes #447
=> fix(arceus): add serebii slug

app/components/info.jsx
check all of gen 8 for locations before deciding the serebii slug
=> feat(home): make serebii link generation smarter

app/components/search-results.jsx
- allow searching by name, case-insensitive. right now, if you search for `Bulba` it wont match anything which is bad
- allow searching by exact national dex number
- allow searching by exact formatted national dex number
=> feat(search): make search a bit better

app/components/search-bar.jsx
missed updating search placeholder text
=> fix(search): update placeholder text

app/components/home.jsx, app/components/notification.jsx, app/utils/state.js
=> feat(home): launch

app/components/dex-edit.jsx, app/components/search-bar.jsx, app/styles/profile.scss, app/styles/tracker.scss
=> fix(styling): misc errors

app/utils/api.js
- don't add extra `?` to the url if there's no query params
- add `x-version` header to all requests so we have that info on the backend
=> feat(api): add version header to all requests

app/utils/rollbar.js
include request and response bodies in telemetry for rollbar. by seeing what was returned by the backend, we can debug issues more easily
=> feat(rollbar): autoInstrument network bodies

.fly/production.toml, .fly/staging.toml, scripts/deploy.sh
- add configs for fly.io
- update deploy.sh to deploy to fly.io instead of kubernetes
=> chore(deploy): move to fly.io

Dockerfile
i forgot to update the Dockerfile when i added typescript in #500
=> fix(typescript): update Dockerfile

config/development.ts, config/local.ts, config/production.ts, config/staging.ts
rollbar recently had a breach, and i think they'll be rotating tokens soon, so in anticipation for that, we're updating our tokens
=> fix(rollbar): update tokens

.eslintrc.js, app/components/library/DexIndicator.tsx, app/components/pages/Account.tsx, app/components/pages/Login.tsx, app/components/pages/Profile/DexCreate.tsx, app/components/pages/Profile/DexEdit.tsx, app/components/pages/Register.tsx, app/components/pages/Tracker/Box.tsx, app/components/pages/Tracker/Info.tsx, app/components/pages/Tracker/SearchBar.tsx, app/styles/main.scss, app/types/dex-types.ts
(*꒦ິ꒳꒦ີ)
- add support for dex type customizations
- make smol changes to support sv dlc
=> feat(dex-types): support customizations

app/components/library/Notification.tsx, app/components/pages/Home.tsx, app/hooks/contexts/use-local-storage-context.tsx
=> feat(sv): teal mask launch

.fly/production.toml, .fly/staging.toml
as a result of change in flyctl, this section is now required
=> fix(deploy): add [[services.ports]] section to fly.tomls
