- app/boot.ts
- app/classes/session.ts
- app/classes/user.ts
- app/components/app.ts
- app/components/nav.ts
- app/components/register.ts
- app/components/tracker.ts
- app/services/api.ts
- app/services/pokemon.ts
- app/services/session.ts
- app/services/user.ts
- app/views/app.html
- app/views/nav.html
- app/views/register.html
- tslint.json
ʕʘ̅͜ʘ̅ʔ
keep in might this is only for registration, nothing else, which means that even if the registration goes through successfully, you won't actually see any signs that you're logged in. to make sure it worked, you can open up the inspector, head to the Resources tab, expand the Local Storage section in the left sidebar, click http://localhost:8080 and you should see `token` and then a string that starts with `eyJ0eX`:
if you want to log out, just select the `token`, delete it, and refresh.
also, since we have no staging env, lemme know after you're done testing so I can purge the db.
- error messages
- password confirm
- optional friend code
- redirect on success
fixes #24 
fixes #29
> feat(register): hook up the register page

- app/components/app.ts
- app/components/dex.ts
- app/components/header.ts
- app/components/home.ts
- app/components/login.ts
- app/components/register.ts
- app/components/tracker.ts
- app/services/session.ts
- app/services/user.ts
- app/views/app.html
- app/views/dex.html
- app/views/header.html
- app/views/login.html
- app/views/register.html
- app/views/tracker.html
ヘ(￣ω￣ヘ)
* moved nav down to login, register, and tracker components, removing it from home
* if logged in, redirect from home, login, and register to your tracker page
* change from `/tracker` -> `/u/:username` and load correct basic info (no captures yet) of the user
* this does not handle user 404's. that will be handled in #43
* by moving nav, it messed up the flexbox configuration, so that needs to be fixed. i tried fixing it and other things broke so i'll leave that to you :)
* when a tracker page is loading, i'm hiding the entire dex component (to simulate loading and because it'll err otherwise), causing some weird stuff (the info component starts at the top). when you add the loading gif, that'll be the time to fix that
* the way it's set up right now, it would be possible to have …
> feat(routes): finalize routing

- app/classes/capture.ts
- app/components/box.ts
- app/components/dex.ts
- app/components/header.ts
- app/components/info.ts
- app/components/pokemon.ts
- app/components/tracker.ts
- app/pipes/group.ts
- app/pipes/number.ts
- app/services/api.ts
- app/services/capture.ts
- app/views/box.html
- app/views/dex.html
- app/views/header.html
- app/views/info.html
- app/views/pokemon.html
- app/views/tracker.html
(๑ॢ˃̶͈̀ ꇴ ˂̶͈́๑ॢ)
- i think we need some sort of "pokemon loading" state when the request to toggle captured state is going through. cause if you click it twice fast, it'll send two `captured = true` requests and even though nothing bad happens (since the second one just fails), ideally, it doesn't make the request.
- also something that happens when you click fast, it sometimes selects the icon/name/number, so maybe disable selection for the pokemon box? idk if people want to be able to copy and paste the pokemon names though...
- for when you aren't logged in (or you're viewing someone else's dex), ive disabled the ability to toggle captures, but the `cursor: pointer` style is still on it, so we should have a way that turns it back to `default`.
- in the same vein, for the empty pokemon …
> feat(captures): load, create, and delete captures

- app/boot.ts
- package.json
- typings.json
- webpack.config.js
＼＼\\୧( ⁼̴̶̤̀ω⁼̴̶̤́ )૭ //／／
- to test, i deployed this branch to the server and so now it's visible at https://pokedextracker.com. things are pretty darn snappy once deployed, so that's nice :+1: 
- since some things changed in `typings.json`, you'll have to re-`npm i` (but you don't have to `rm -rf node_modules`) once this is merged
fixes #35
> feat(deploy): add prod configs to deploy

- app/components/box.ts
- app/components/dex.ts
- app/components/info.ts
- app/components/pokemon.ts
- app/components/tracker.ts
- app/styles/tracker.scss
- app/views/box.html
- app/views/dex.html
- app/views/info.html
- app/views/pokemon.html
- app/views/tracker.html
꒳ᵃ꒳ᵃ꒳ᵃ~(๑°ᗨૢ°๑)♡ӵᵉ੨ᑋ✧
fixes https://github.com/robinjoseph08/pokedextracker.com/issues/17
- adds collapsible info panel
- uses that collapse functionality for a better responsive/mobile experience
still needs:
> feat(info): collapsible info panel

- app/views/pokemon.html
へ‿(ツ)‿ㄏ
fixes https://github.com/robinjoseph08/pokedextracker.com/issues/80
you must have been working on this at the same time that i was doing the responsiveness changes where i had to make duplicates of `set-caputred`, so i probably left this out in a rebase.
> fix(font): fix m/f sign for set-captured-mobile

- app/components/header.ts
- app/directives/off-click.ts
- app/views/header.html
ꉂ ૮( ᵒ̌ૢꇴᵒ̌ૢ )ა｡*ﾟ✧
fixes #104 
it works perfectly on desktop, but on mobile, for the "clicking out" to work, you need to click on "something". essentially, it works if you change the focus e.g. i have the region dropdown open and then i mark bulbasaur as captured. thats at least a step up from what it is currently (it stays open forever unless you explicitly close it).
> feat(tracker): close things when clicking outside

- app/boot.ts
- app/classes/pokemon.ts
- app/components/app.ts
- app/components/box.ts
- app/components/header.ts
- app/components/info.ts
- app/components/login.ts
- app/components/nav.ts
- app/components/pokemon.ts
- app/components/register.ts
- app/views/header.html
- app/views/info.html
- app/views/pokemon.html
- npm-shrinkwrap.json
- package.json
- public/index.html
૮( ᵒ̌ૢ௰ᵒ̌ૢ )ა
im learning all sorts of things about google analytics! did you know you can track custom events? and it turns out our page tracking was wrong since it's all a single page app (russell pointed that out to me). thats why we never saw `/login` or `/register` page views, cause it wasn't correctly tracking page transitions, only the first landing.
so this pr fixes that and adds tracking for several ga events. a ga event consists of an `action`, a `category`, an optional `label`, and an optional `value`. i use the first 3, but i don't use `value` cause it has to be an integer, and i dont like that.
the events ive added tracking for:
category | action | label | notes
---|---|---|---
Session | login
Session | register
Session | sign out
Pokemon | mark | the pokemon's name
Pokemon | …
> feat(analytics): track all the things!

- app/styles/main.scss
- app/styles/tracker.scss
щ(ಠ益ಠщ)
fixes https://github.com/robinjoseph08/pokedextracker.com/issues/122, if you are curious here is the reasoning: http://stackoverflow.com/questions/33790219/firefox-not-respecting-flex-shrink
ss of firefox below, verified that it still works in chrome and mobile. since my safari is still broken... can you verify that? interestingly enough, prod (pokedextracker.com) is totally fine for me in safari, it's only broken locally. CLUES!!!
> fix(styles): fix firefox bugs

- app/boot.ts
- app/services/api.ts
- config/development.ts
- config/index.ts
- config/production.ts
- config/staging.ts
- webpack.config.js
(๑•̀ㅂ•́)و✧
**finally** adds the configs to support a staging env!
you should run it and make sure it still runs, but now, itll be talking to the staging api. so no accounts exist there. i made another `ashketchum10` so the homepage works and i populated the db with pokemans so it should be good to go!
> feat(config): add configs for each environment

- app/components/dex.ts
- app/components/tracker.ts
- app/styles/tracker.scss
- app/views/dex.html
- app/views/tracker.html
ෆු(*˃ர்˂*)ෆු
fixes https://github.com/robinjoseph08/pokedextracker.com/issues/117
can you add the actual back-to-top functionality for the button? also, ideally it's not there if you're at the top and only shows up maybe 50-100px down. also it'd be cool if it animated and slid in from the bottom (bonus cookie points!!).
one caveat for the scrollbar now being within the dex area + clickable - if you're in a weird "mid" state, but the info panel is expanded, the scroll bar is on the right within the info area. it's pretty unavoidable though since, in that mode, the panel is essentially absolutely positioned. i think it's fine though, because the rest of the time the scrollbar is exposed as expected.
> feat(dex): clickable scroll bar + back to top btn

- app/boot.ts
- app/components/box.ts
- app/components/dex.ts
- app/pipes/group.ts
- app/views/box.html
- app/views/dex.html
- app/views/evolution-family.html
- app/views/evolutions.html
- app/views/header.html
- app/views/info.html
- npm-shrinkwrap.json
- package.json
(۶* ‘ꆚ’)۶”
updated to the latest beta! from here, ill update to the latest rc but thats probably a bigger change.
changes include (for documentation purposes):
- importing `bootstrap` from `angular2/platform/browser` instead of `'angular2/bootstrap` (added in beta.15)
- pipes take variable args instead of an array (added in beta.16)
- change syntax of `*ngFor` from `#item of items` to `let item of items` (added in beta.17)
- remove `providers: [ElementRef]` (don't know why, but it was apparently breaking everything, showed no errors, and took forever to debug -_-)
@ami all you need to do is checkout the branch, `npm i`, `npm start`, and see if all of the pages/functionality still works! hopefully we have more luck than in #127
> chore(deps): upgrade angular beta.12 -> beta.17

- webpack.config.js
( ≧Д≦)
forgot this in #152 ...oops
> fix(webpack): remove reference to istanbul-instrumenter

- app/styles/main.scss
- app/styles/tracker.scss
(๑ˇ ῁̫ ˇ)˒˒
^ smug 🐛  catching face
the disabled spinner button on the account page wasn't actually working as expected b/c all the styles for it were nested under `box .box-header button`.
> fix(spinner): hide content when spinning

- npm-shrinkwrap.json
- package.json
- webpack.config.js
ฅ(*°ω°*ฅ)
fixes #190 
right now, master is broken for ie 11 (and others). this fixes that! i tested it with my vm! it provides a Promise polyfill and i _think_ a localStorage polyfill too (we've had a few issues with that too).
i also saved the `raw-loader` in the package.json and the shrinkwrap. not sure why it wasnt there before... ¯\\\_(ツ)_/¯
> fix(polyfill): add babel-polyfill

- .eslintrc
- app/components/dex.jsx
(*′☉.̫☉)
fixes #191 
as the issue says, there is a weird occurrence where `this._dex` is `null`. this just checks to make sure that it exists first.
also i dont like the `no-confusing-arrow` rule. its dumb. so i removed it! :radioactive:
> fix(scroll): check if _dex exists

- app/index.jsx
(◍˃̶ᗜ˂̶◍)ﾉ”
fixes #192 
as mentioned in the issue, it should wait for the dom to be loaded before trying to load react cause if you try to do so before, it errs out. this should fix that by waiting for `DOMContentLoaded`.
> fix(load): wait for DOMContentLoaded if necessary

- app/actions/capture.js
- app/actions/dex.js
- app/actions/user.js
- app/components/dex.jsx
- app/components/mark-all-button.jsx
- app/components/pokemon.jsx
- app/components/progress.jsx
- app/components/tracker.jsx
- app/reducers/captures.js
- app/reducers/current-dex.js
- app/reducers/current-user.js
- app/reducers/dexes.js
- app/reducers/index.js
- app/reducers/users.js
(ꐦ°᷄д°᷅)
this is the same commit from #199, but merging to master instead of the feature branch, except it's also passing `dex` when saving/deleting captures. as i was testing #203, i created a shiny dex for `/u/hiami` which was the third dex for that account but every time i marked a pokemon as captured, it didnt actually mark it as captured in the db. this is cause the endpoint just picks a random dexs to create the captures for lol. but for the api to use a dex id thats being passed in, this needs to be in master.
you should just make sure that everything still works as expected (particularly users with only one dex)!
> refactor(dexes): use the dexes API for the tracker page

- .travis.yml
- app/actions/user.js
- app/components/account.jsx
- app/components/evolution-family.jsx
- app/components/home.jsx
- app/components/info.jsx
- app/components/login.jsx
- app/components/pokemon.jsx
- app/components/register.jsx
- app/styles/main.scss
- app/styles/profile.scss
- app/styles/tracker.scss
- app/utils/pokemon.js
- npm-shrinkwrap.json
- package.json
(੭ु´͈ ᐜ `͈)੭ु⁾⁾
- add dex settings to signup
- use shiny sprites on tracker page if dex is shiny
- i added the dex stuff beneath the user stuff in one column, which i think is fine - but it's a bit weird when you submit the form and there's an error because you have to scroll back up to see the error. any way for us to auto-scroll up to the error? alternatively, i can refactor the register page to be two columns instead if you think that's better
- after registration, you get redirected to the profile page. do you think that's preferred or should we send you directly to your first dex?
> feat(dexes): add dex settings to signup

- app/components/evolutions.jsx
- app/components/info.jsx
(⋆ॢʾ ˙̫̮ ʿ⋆ॢ)
stop relying on the returned props so that we can generate them based on dex. this is necessary for gen vii support. this is blocking https://github.com/robinjoseph08/api.pokedextracker.com/pull/69 so we should deploy this as soon as its merged!
i also noticed that we were missing some spaces. some examples of why we need it:
i dont think adding these spaces will hurt if they arent needed, right?
> refactor(info): generate urls on the front-end and add spaces

- app/components/nav.jsx
¯\_╏ ՞ ︿ ՞ ╏_/¯
fixes https://github.com/pokedextracker/pokedextracker.com/issues/223
quick fix to allow the dropdown to work on mobile. you can't "un"click it to make it go away, but at least it works now! not sure if there's an "actual" fix other than just making a mobile-only version of the dropdown that is based off clicks instead of hover.
> fix(nav): fix dropdown for mobile

- app/actions/pokemon.js
- app/components/box.jsx
- app/components/dex.jsx
- app/components/evolution-family.jsx
- app/components/info.jsx
- app/components/mark-all-button.jsx
- app/components/pokemon.jsx
- app/components/tracker.jsx
- app/reducers/captures.js
- app/reducers/pokemon.js
- app/utils/pokemon.js
(:D)┼─┤
this pr shouldnt actually change anything. its just changing to gradually use some of the newer backend stuff so we can make the change to forms.
to test just make sure that everything still works. just check the things pokemon related (i.e. you dont need to check the account/login stuffs)
> refactor(pokemon): use pokemon.id instead of pokemon.national_id

- app/components/dex-edit.jsx
- app/components/dex-indicator.jsx
(((ლ(͏ ͒ • ꈊ • ͒)ლ)))♡
- adds "region" label next to shiny and generation labels
- adds region to edit dex. "warning" display is based on this logic:
original | editing to | warning
------- | ---------- | ------
Gen 6 | Gen 7 Regional | Any non-Alola Dex capture info will be lost.
Gen 6 | Gen 7 National | No warning needed.
Gen 7 National | Gen 6 | Any Gen 7 capture info will be lost.
Gen 7 Regional | Gen 6 | Any Gen 7 capture info will be lost.
Gen 7 National | Gen 7 Regional | Any non-Alola Dex capture info will be lost.
Gen 7 Regional | Gen 7 National | No warning needed.
> feat(edit): add region to edit dex

- .travis.yml
- app/components/box.jsx
- app/components/dex-create.jsx
- app/components/dex-edit.jsx
- app/components/dex-indicator.jsx
- app/components/info-locations.jsx
- app/components/info.jsx
- app/components/region.jsx
- app/components/register.jsx
- app/utils/pokemon.js
( ⚆ _ ⚆ )
- change usage of `generation`/`region` to use `game`/`regional` instead since api is completely using those as the source of truth instead
- mostly in user create, dex create, dex edit
- there are still a few refs to the props, but its for the region filter that will be removed in the usum pr
- update some travis stuffs
to test, just make sure that everything behaves as normal! this is just an internals pr so nothing user-facing shouldve changed
> chore(game): replace usage of generation/region with game/regional

- app/components/box.jsx
(ට˓˳̮ට๑)
checked all of them, and this makes it so it only shows on national sumo and national usum, not national oras or regional sumo or usum
> fix(box): only show alolan box on national dexes

- app/styles/main.scss
⌒ﾟ(❀>◞౪◟<)ﾟ⌒
- fixes https://github.com/pokedextracker/pokedextracker.com/issues/301
- makes modal always fit on 80% of the height of the screen and allows the rest of the content to be scrollable:
> fix(modal): make modal vertically scrollable

- app/components/nav.jsx
- app/styles/main.scss
@(o・ェ・)@ノ
sets a max height on the dex list, purposely cuts it off at dex 6.5 to indicate to the user to scroll. i left the profile, settings, and sign out there always.
what do you think? i can always change it up, reorder things, etc.
fixes #305
> fix(dropdown): add scroll for over 6 dexes

- app/actions/game.js
- app/components/dex-create.jsx
- app/components/dex-edit.jsx
- app/components/dex.jsx
- app/components/register.jsx
- app/reducers/games-by-id.js
- app/reducers/index.js
°₊·ˈ∗(( ॣ>̶᷇ᗢ<̶᷆ ॣ))∗ˈ‧
- instead of relying on `NATIONAL_ONLY_GAMES`, rely on db value of `regional_support`
- i also made the db have `regional_support = true` for xy, oras, sumo, and usum so we'll support regional gen 7 dexes as well
- rely on `national_support` to potentially not allow national dexes for a game. this isnt used now, but will be for lets go
- the default value for "new dex" is always the latest game
- change all references to specific games (e.g. the word alolan in various places)
- fixes #311
> feat(games): use regional_support and national_support

- public/robots.txt
- public/sitemap.xml
(๏็ટૄ ๏็ (๏็ટૄ◟๏็ )
i was perusing our search console and i noticed that a ton of our search results are peoples profiles/dexes. and i think thats kinda lame, so we're just not gonna index them anymore.
i was wondering about ashketchum10, but tbh, i dont think thats a super valuable landing page anyway. if they hit the homepage, they can go to his profile that way instead of hitting it directly. and that way, they have more context into what the site is. but if you disagree, lmk!
> feat(robots): disallow /u/ pages from being indexed

- app/components/profile.jsx
(´･(00)･｀)
while clicking through the site, id get an error every now and then complaining about `Cannot read property 'id' of undefined` resulting in the page not loading. according to sentry, this actually happens a lot. it looks like the root cause is because the dex create component assumes that the games have already been loaded, but since we werent waiting on it before marking `loading` as `false` in the profile, there was a race condition where the games werent loaded in time.
this change now waits on the games too before marking `loading` as `false`
> fix(profile): wait for games to load

- app/styles/index.scss
- app/styles/tracker.scss
ε-(‘ﾍ´○)┓
set default shellos/gastrodon to east sea, since explicitly only east sea shellos can be captured in swsh. this also sets east sea to be the only form on all other dexes, but that's fine since we don't track forms currently anyway.
normal:
shiny:
> chore(sprites): swap shellos and gastrodon forms

- Dockerfile
(๑°o°๑)
set `NODE_ENV` to `production` so that the `bundle.js` gets minified and uglified. currently, the `bundle.js` is ~10.3MB (gzipped: ~1.7MB), and with this change it's now ~2.5MB (gzipped: ~272KB) which is ~6.5x improvement. this should help reduce some data transfer costs
i also updated nginx cause why not
just gonna merge this since its a small change!
> fix(docker): set NODE_ENV to be production to uglify bundle

- config/index.js
(⁎˃ᆺ˂)
when i deployed #365 to staging, it didn't work cause now, we're always hardcoding production for the deployed versions. so i reordered the environment checks so that it will always pull the correct environment in staging and production (based on the hostnames), and then it will look for any `NODE_ENV` (so that `NODE_ENV=local yarn start` will still work), and lastly, it will default to `development` (so that `yarn start` still hits staging api). so i think this fixes everything
merging againnn
> fix(config): change priority of environment

- .dockerignore
- .gitignore
- Dockerfile
- scripts/deploy.sh
- webpack.config.js
(꒪ȏ꒪)ｴｯ?
- we're seeing a lot of errors on older versions of the code (code that was deployed months ago). my suspicion is that it's just an aggressive browser that causing it, so by adding some basic cache busting (following [this](https://webpack.js.org/guides/caching/)), it will help it. however, i'm not 100% sure about this. cause if the `index.html` is the thing that's being cached and not the `bundle.js`, then it will continue to pull the old `index.html` because it's hard to cache bust that. though our headers should already be doing that, so let's hope that all works.
- refine .gitignore and `.dockerignore` to handle the new files generated through the cache busting
- [unrelated] move the build arg further down in the `Dockerfile` so that we can better use docker cache when …
> feat(deploy): add cache busting

- package.json
- webpack.config.js
- yarn.lock
(／\_^)／ 　　　　　　●　＼(^\_＼)
- during the react upgrade, i removed `isomorphic-fetch` from our dependencies cause i thought that `fetch` was pretty mainstream at this point, and we could remove an extra dependency. since that change was deployed, we have seen some `'fetch' is undefined` errors. and when looking at the browser breakdown, its only IE browsers and Edge 13. thats cause IE never supported `fetch` and Edge only got it in version 14. so it checks out. there isnt a lot of traffic with these browsers, but might as well add this tiny polyfill to support it. and i went directly to `whatwg-fetch` this time cause its supported by github instead of `isomorphic-fetch` which hasn't been updated since 2016.
- with my cache busting PR, i broke being able to run it locally. this fixes that.
> fix(fetch): add fetch polyfill

- nginx.conf
(*′☉.̫☉)
- gzip svgs in addition to the other mime types
- for images: cache it normally
- for images and jss/css: dont have a `try_files` directive which will end up returning the contents of `index.html`. we want this for most urls e.g. `/login` should still return the contents of `index.html` so that react router can take over and display the correct page. but we dont want assets to do that. i have a feeling this might be whats cause so many old versions of the code to still be out in the wild. hopefully, if it accurately returns a 404, it will indicate to the browser that it needs to refetch things
> fix(nginx): refine caching

- app/components/box.jsx
instead of relying on `${game_family_id}_id` on the pokemon, just rely on the simpler `dex_number`. this is the accompanying change for https://github.com/pokedextracker/api.pokedextracker.com/pull/132
> feat(box): rely on dex_types_pokemon.dex_number

- nginx.conf
- hopefully make the no-caching we have for our html better so we really dont cache it
- make sure we are caching our bundle js since we've added the content hash to the file a while ago, so if it changes, it will have a different hash. the fetching of that new file should be handled by the fact that we're not caching the html (since that's what references the js file name), but since the filenames are unique (instead of always being called `bundle.js` or something, we actually do want to cache it. it shouldn't change. and it could save us some bandwidth costs.
> fix(cache): adjust our caching policies

- app/components/search-results.jsx
i missed a few places where we're checking the number. so it works for `1` as well as `001` (and `0001`)
> fix(search): search against corrected national id and dex id

- app/components/dex-create.jsx
- app/components/dex-edit.jsx
- app/components/register.jsx
pass the slug that's generated on the frontend to the backend so that the backend doesn't need to deal with slug generation logic anymore
> feat(slug): pass slug through to backend

- app/components/account.jsx
only pass through the password if it's being edited. otherwise, send undefined. normally, we treat the empty string as wanting to clear it out. but we never want to do that for the password, so passing the empty string is a bit weird.
> fix(account): only pass through the password if it's being edited
